"use client";

import { FormEvent, useState } from "react";
import { Loader2, Search, Trophy } from "lucide-react";

type Match = { gameId: number | null; characterCode: number | null; rank: number | null; kills: number; assists: number; mode: number | null; teamMode: number | null; startedAt: number | null; };
type SearchResult = { player: { nickname: string }; stats: { totalGames: number; totalWins: number; averageRank: number | null; averageKills: number | null; mmr: number | null } | null; matches: Match[]; };

export function EternalReturnSearch() {
  const [nickname, setNickname] = useState(""); const [result, setResult] = useState<SearchResult | null>(null); const [error, setError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const query = nickname.trim(); if (!query) return; setIsLoading(true); setError(null); try { const response = await fetch(`/api/eternal-return?nickname=${encodeURIComponent(query)}`); const payload = await response.json() as SearchResult & { message?: string }; if (!response.ok) throw new Error(payload.message || "전적을 불러오지 못했습니다."); setResult(payload); } catch (requestError) { setResult(null); setError(requestError instanceof Error ? requestError.message : "전적을 불러오지 못했습니다."); } finally { setIsLoading(false); } }
  return <section className="mt-8"><form onSubmit={handleSubmit} className="flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="eternal-return-nickname">이터널 리턴 닉네임</label><input id="eternal-return-nickname" value={nickname} onChange={(event) => setNickname(event.target.value)} maxLength={24} placeholder="게임 닉네임을 입력하세요" className="min-w-0 flex-1 rounded-xl border border-[#c7d2fe] bg-white px-4 py-3 text-[#17202a] outline-none transition placeholder:text-[#94a3b8] focus:border-[#4f46e5] focus:ring-4 focus:ring-[#e0e7ff]" /><button disabled={isLoading} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#4338ca] px-5 py-3 font-black text-white transition hover:bg-[#3730a3] disabled:cursor-not-allowed disabled:bg-[#a5b4fc]">{isLoading ? <Loader2 size={18} className="animate-spin" /> : <Search size={18} />}{isLoading ? "조회 중" : "전적 검색"}</button></form>{error ? <p role="alert" className="mt-4 rounded-xl border border-[#fecaca] bg-[#fff1f2] px-4 py-3 text-sm font-bold text-[#b42318]">{error}</p> : null}{result ? <Results result={result} /> : null}</section>;
}
function Results({ result }: { result: SearchResult }) { const { stats } = result; const winRate = stats?.totalGames ? Math.round((stats.totalWins / stats.totalGames) * 100) : null; return <div className="mt-6 space-y-5"><section className="rounded-2xl border border-[#c7d2fe] bg-white p-5 shadow-sm sm:p-6"><p className="text-sm font-black uppercase tracking-wider text-[#4f46e5]">Eternal Return Player</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><h2 className="text-2xl font-black text-[#17202a]">{result.player.nickname}</h2>{stats?.mmr !== null && stats?.mmr !== undefined ? <span className="rounded-full bg-[#eef2ff] px-3 py-1.5 text-sm font-black text-[#3730a3]">RP {stats.mmr.toLocaleString()}</span> : null}</div>{stats ? <div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#e0e7ff] pt-5 sm:grid-cols-4"><Metric label="시즌 경기" value={`${stats.totalGames}판`} /><Metric label="1위" value={`${stats.totalWins}회`} /><Metric label="승률" value={winRate === null ? "-" : `${winRate}%`} /><Metric label="평균 순위" value={stats.averageRank === null ? "-" : stats.averageRank.toFixed(2)} /></div> : <p className="mt-5 border-t border-[#e0e7ff] pt-5 text-sm text-[#64748b]">시즌 통계는 서버에 <code>ETERNAL_RETURN_CURRENT_SEASON_ID</code>를 설정하면 함께 표시됩니다.</p>}</section><section className="overflow-hidden rounded-2xl border border-[#dbe4f0] bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-[#e8edf5] px-5 py-4"><Trophy size={18} className="text-[#4f46e5]" /><h2 className="font-black text-[#17202a]">최근 매치</h2><span className="text-sm font-bold text-[#64748b]">{result.matches.length}건</span></div>{result.matches.length ? <ul className="divide-y divide-[#e8edf5]">{result.matches.map((match, index) => <li key={match.gameId ?? index} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="font-black text-[#17202a]">{match.rank ? `${match.rank}위` : "순위 정보 없음"} <span className="ml-2 text-sm font-semibold text-[#64748b]">{modeLabel(match.mode, match.teamMode)}</span></p><p className="mt-1 text-sm text-[#64748b]">{match.characterCode ? `캐릭터 #${match.characterCode}` : "캐릭터 정보 없음"}{match.startedAt ? ` · ${formatDate(match.startedAt)}` : ""}</p></div><p className="rounded-lg bg-[#f5f3ff] px-3 py-2 text-sm font-black text-[#4338ca]">{match.kills} 킬 · {match.assists} 어시스트</p></li>)}</ul> : <p className="px-5 py-10 text-center text-sm text-[#64748b]">최근 90일 내 매치 기록이 없습니다.</p>}</section></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold text-[#64748b]">{label}</p><p className="mt-1 text-xl font-black text-[#17202a]">{value}</p></div>; }
function modeLabel(mode: number | null, teamMode: number | null) { const type = mode === 3 ? "랭크" : mode === 2 ? "일반" : "매치"; const team = teamMode === 1 ? "솔로" : teamMode === 2 ? "듀오" : teamMode === 3 ? "스쿼드" : null; return team ? `${type} · ${team}` : type; }
function formatDate(value: number) { const date = new Date(value > 10_000_000_000 ? value : value * 1000); return Number.isNaN(date.getTime()) ? "" : new Intl.DateTimeFormat("ko-KR", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(date); }
